---
title: "Aquaculture Model"
date: "`r Sys.Date()`"
output: pdf_document
---

#####Objective: Step through optimal harvest and planting decisions by a generic totoaba farm..

Toy Model:

Von Bertalanffy Growth Model

$L(t) = L_\infty ( 1 - e^{ - K ( t - t_0 )})$

```{r growth_function}

# Von Bertalanffy estimation(s) for totoaba.

fn_vb = function(linf, k, t, t_0){l = linf * ( 1 - 10 ^ ( - k * ( t - t_0)))}

test = fn_vb(20, 50, 5, 0.5)

```

Weight-Length Conversion

Equation Name

$Equation!$

```{r wl_function}

```




```{r pkg_ins, include = FALSE}

# Check out knitr for knitr::read_chunk.
library(knitr)

# Name packages.
pkg <- c("readr",
         "knitr",
         "tidyverse",
         "gapminder",
         "sandwich",
         "broom",
         "stargazer",
         "cowplot")

# Install packages.
#install.packages(pkg, verbose = FALSE, quiet = TRUE)

  
# Update packages.
#update.packages(pkg, verbose = FALSE, quiet = TRUE)

# Check out packages.
lapply(pkg, library, character.only = TRUE)

```






#####Appendix: LaTeX Demo

$$ d_i = \alpha_{0, i} - \alpha_{1, i} * x_{emissions} + u_i$$