---
title: "Aquaculture Model"
date: "`r Sys.Date()`"
output: pdf_document
---

#####Objective: Step through optimal aggregate harvest in an open access fishery.

Gordon-Schaefer Model / INAPESCA 2018



Add a formalized reference.

Walk through system of equations with salient outputs.

```{r pkg_ins, include = FALSE}

# Check out knitr for knitr::read_chunk.
library(knitr)

# Name packages.
pkg <- c("readr",
         "knitr",
         "tidyverse",
         "gapminder",
         "sandwich",
         "broom",
         "stargazer",
         "cowplot",
         "kableExtra")

# Install packages.
#install.packages(pkg, verbose = FALSE, quiet = TRUE)

  
# Update packages.
#update.packages(pkg, verbose = FALSE, quiet = TRUE)

# Check out packages.
lapply(pkg, library, character.only = TRUE)

```

#####1. Deterministic Logistic Growth Demo

```{r function}

# Growth references growth instead of stock. Merp.
grow_log = function(r, K, n0, start, end){
                     v_n = as.numeric(vector(length=(end - start)))
                     v_n[1] = n0
                     t = length(seq(start, end))
            for (i in 2:t){v_n[i] = r * v_n[i - 1] * (1 - v_n[i - 1] / K)}
                     return(v_n)}

v_grow_log = grow_log(0.01, 50, 1, 2000, 2025)

```



```{r figure}

plot(v_grow_log)

```


#####Appendix: LaTeX Demo

$$ d_i = \alpha_{0, i} - \alpha_{1, i} * x_{emissions} + u_i$$